version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Copying Glue scripts to S3..."
      - aws s3 cp --recursive ./scripts s3://aws-glue-assets-407717415880-us-east-1/scripts/
  post_build:
    commands:
      - echo "Build and deployment process complete!!!"
